name: Playwright CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Tests
        run: npx playwright test
        continue-on-error: true

      - name: Generate Summary
        run: node scripts/report-summary.js

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Upload Screenshots & Videos
        uses: actions/upload-artifact@v4
        with:
          name: test-results-artifacts
          path: test-results/

      - name: Send Email Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Playwright Test Execution Report"
          body: |
            🚀 Playwright CI Execution Completed

            $(cat summary.txt)

            📎 Full HTML Report attached.
          attachments: |
            playwright-report/index.html
            summary.txt